### ISSUE TITLE
suggestion- ability to link to other mdn pages?

### ISSUE THREAD

**Issue by magic8baller** [samundrak/vscode-esdoc-mdn#10]
Hey I was wondering if it would be possible to click on internal MDN links with the webview API? I'm not famiilar at all with VScode apis but that would be awesome.
I glanced through their webview docs and I saw something about dynamic html content, but seems like they warn against 'heavy use' so I don't know much about it or performance implications. if it's feasible and you don't have the time i could take a stab at it

**Comment by samundrak** [comment]
hi @magic8baller ,
Sorry for the late response,
I don't know why GitHub didn't send me a notification about this issue.
I would love to see a PR from you regarding this issue.
Thank you
