### ISSUE TITLE
MDN stylesheets not loading

### ISSUE THREAD

**Issue by parkerault** [samundrak/vscode-esdoc-mdn#11]
The search tab opens as expected, but none of the sylesheets are loaded and none of the links are visible (I suspect they are the same color as the background). This is the only ouput I see in dev tools:

```
[Embedded Page] Blocked script execution in 'data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%0D%0A%3Chtml%20lang%3D…100%25%3B%20height%3A%20100%25%22%3E%0D%0A%3C%2Fbody%3E%0D%0A%3C%2Fhtml%3E' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

Screenshot:

![image](https://user-images.githubusercontent.com/78856/57319814-15e87400-70c3-11e9-9011-b1fa60ca6615.png)

This extension seems very useful so I'd really like to use it!

**Comment by samundrak** [comment]
Thanks, i will try to fix this issue, if you like you can also contribute by opening a PR for this issue :+1:
