### ISSUE TITLE
After one failure to find documentation, the extension stops working

### ISSUE THREAD

**Issue by danyalaytekin** [samundrak/vscode-esdoc-mdn#2]
Visual Studio Code 1.24.0
ESDoc MDN 0.4.0
macOS 10.13.5

----

If the extension ever fails to find some documentation on MDN, the extension will not try to find documentation again when a valid instruction is given.  This is can be resolved by restarting VS Code.

To reproduce:

1. Type something for which documentation doesn't exist on MDN, e.g. `//mdn sinon.stub;`.
1. Observe that the extension responds with `No documentation found about "sinon.stub"`.
1. Close the extension's results page.
1. Type something for which documentation does exist, e.g. `//mdn array.length;`.
1. Observe that the extension does not respond.

**Comment by samundrak** [comment]
Hey, thanks for the issue, I will be working on it asap :+1:

**Comment by samundrak** [comment]
#3
